version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: betting_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: betting_backend
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: betting_db
      JWT_SECRET: supersecretkey
    ports:
      - "5000:5000"

  frontend:
    build: ./apps/frontend
    container_name: betting_frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://backend:5000
    ports:
      - "5173:5173"

volumes:
  postgres_data:
