version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: betting_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
    container_name: betting_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: betting_db
    working_dir: /app/apps/backend
    command: ["yarn", "dev"]

volumes:
  postgres_data:
